export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";
export const SET_SUCESS = "SET_SUCESS";
export const SET_USER = "SET_USER";
export const SET_LOADING = "SET_LOADING";
export const GET_ANNOUNCMENT = "GET_ANNOUNCMENT";
export const CREATE_EXAM_STUDENT = "CREATE_EXAM_STUDENT";
